# Employee Attrition Prediction Project By Phitron

## ML Final Exam Project

In this notebook I follows the required roadmap to accomplish the project

1. Data Loading
2. Data Preprocessing
3. ML Pipeline Creation
4. Primary Model Selection
5. Model Training
6. Cross-Validation
7. Hyperparameter Tuning
8. Best Model Selection
9. Model Evaluation
10. Gradio Web Interface
11. Hugging Face Deployment Preparation

In [1]:
# Import all the required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)

import joblib

Matplotlib is building the font cache; this may take a moment.

# Step 1: Data Loading

Load Employee Attrition dataset and check the dataset structure using head()

In [2]:
# Load dataset
data = pd.read_csv("WA_Fn-UseC_-HR-Employee-Attrition.csv")

data.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [3]:
# Dataset shape

data.shape

(1470, 35)

# Step 2: Data Preprocessing

The preprocessing steps include:

- Checking missing values
- Removing unnecessary features
- Separating target variable
- Encoding categorical variables
- Scaling numerical features

In [4]:
# Check missing values
data.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In this dataset, there is no missing values, so before do encoding string columns
Let's separate first target values

In [10]:
# Separate features and target
X = data.drop("Attrition", axis=1)
y = data["Attrition"]

# Convert target into binary format
y = y.map({"No": 0, "Yes": 1})

print(X.shape)
print(y.shape)

(1470, 34)
(1470,)

Before jump to encoding remove unnecessary columns, which actually don't need to predict the model

In [11]:
# Remove unnecessary features, after thinking about columns

remove_columns = [ "EmployeeCount", "EmployeeNumber","StandardHours", "Over18"]

X = X.drop(columns=remove_columns)

X.head()

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,94,...,3,1,0,8,0,1,6,4,0,5
1,49,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,61,...,4,4,1,10,3,3,10,7,1,7
2,37,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,92,...,3,2,0,7,3,3,0,0,0,0
3,33,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,56,...,3,3,0,8,3,3,8,7,3,0
4,27,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,40,...,3,4,1,6,3,3,2,2,2,2

Verify the dataset does those columns removed or not

In [13]:
X.columns

Index(['Age', 'BusinessTravel', 'DailyRate', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EnvironmentSatisfaction', 'Gender',
       'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole',
       'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'MonthlyRate',
       'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='str')

Here, can see above cell results, that scripts successfully removed the unnecessary features

# Step 3: Train-Test Split

The dataset is divided into training and testing sets before model training.

In [14]:
X_train, X_test, y_train, y_test = train_test_split( X,y,test_size=0.2, random_state=42, stratify=y )

# Step 4: Pipeline Creation

In [15]:
numeric_features = X.select_dtypes( include=["int64", "float64"]).columns

categorical_features = X.select_dtypes( include=["object"]).columns


numeric_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])


categorical_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])


preprocessor = ColumnTransformer([
    ("num", numeric_transformer, numeric_features),
    ("cat", categorical_transformer, categorical_features)
])

/var/folders/gd/9ttr_8_x3djg_nv8fzkh4vgm0000gn/T/ipykernel_5726/1100311671.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = X.select_dtypes( include=["object"]).columns

# Step 5: Primary Model Selection

Random Forest is selected because it can capture nonlinear relationships, handle feature interactions, and perform well on tabular classification problems.

In [16]:
model = RandomForestClassifier(random_state=42)

pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", model)
])

# Step 6: Model Training

In [17]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['Age', 'DailyRate', 'DistanceFromHome', 'Education',
       'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel',
       'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWork...
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='str')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole',
       'MaritalStatus', 'OverTime'],
      dtype='str'))])),
                ('model', RandomForestClassifier(random_state=42))])

# Step 7: Cross-Validation

In [18]:
cv_scores = cross_val_score(
    pipeline,
    X_train,
    y_train,
    cv=5,
    scoring="accuracy"
)

print("CV Scores:", cv_scores)
print("Average Score:", cv_scores.mean())
print("Standard Deviation:", cv_scores.std())

CV Scores: [0.86016949 0.87659574 0.86382979 0.87659574 0.84255319]
Average Score: 0.863948791922106
Standard Deviation: 0.01258538692012012

# Step 8: Hyperparameter Tuning

In [19]:
parameter_grid = {
    "model__n_estimators": [100, 200],
    "model__max_depth": [None, 5, 10],
    "model__min_samples_split": [2, 5]
}


grid_search = GridSearchCV(
    pipeline,
    parameter_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)


grid_search.fit(X_train, y_train)

print(grid_search.best_params_)
print(grid_search.best_score_)

{'model__max_depth': 10, 'model__min_samples_split': 2, 'model__n_estimators': 100}
0.8656509195816804

# Step 9: Best Model Evaluation

In [20]:
best_model = grid_search.best_estimator_

y_pred = best_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

if hasattr(best_model, "predict_proba"):
    print("ROC-AUC:", roc_auc_score(y_test, best_model.predict_proba(X_test)[:,1]))

Accuracy: 0.8435374149659864
              precision    recall  f1-score   support

           0       0.86      0.98      0.91       247
           1       0.55      0.13      0.21        47

    accuracy                           0.84       294
   macro avg       0.70      0.55      0.56       294
weighted avg       0.81      0.84      0.80       294

[[242   5]
 [ 41   6]]
ROC-AUC: 0.7819794986648291

# Step 10: Save Model for Deployment

In [21]:
joblib.dump(best_model, "employee_attrition_pipeline.pkl")

['employee_attrition_pipeline.pkl']

# Step 11: Gradio Interface Preparation

The saved pipeline can be loaded in app.py and deployed to Hugging Face Spaces.

In [ ]:
# Example loading code for deployment

# model = joblib.load("employee_attrition_pipeline.pkl")